version: '3.8'

services:
  backend-1:
    build:
      context: ./simple-backend-service
    environment:
      - SERVER_PORT=8081
      - BACKEND_ID=backend-1
    ports:
      - "8081:8081"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8081/health" ]
      interval: 10s
      timeout: 5s
      retries: 5

  backend-2:
    build:
      context: ./simple-backend-service
    environment:
      - SERVER_PORT=8082
      - BACKEND_ID=backend-2
    ports:
      - "8082:8082"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8082/health" ]
      interval: 10s
      timeout: 5s
      retries: 5

  backend-3:
    build:
      context: ./simple-backend-service
    environment:
      - SERVER_PORT=8083
      - BACKEND_ID=backend-3
    ports:
      - "8083:8083"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8083/health" ]
      interval: 10s
      timeout: 5s
      retries: 5

  hash-router-service:
    build:
      context: ./hash-router-service
    environment:
      - ROUTER_NODES_0_ID=backend-1
      - ROUTER_NODES_0_HOST=backend-1
      - ROUTER_NODES_0_PORT=8081
      - ROUTER_NODES_1_ID=backend-2
      - ROUTER_NODES_1_HOST=backend-2
      - ROUTER_NODES_1_PORT=8082
      - ROUTER_NODES_2_ID=backend-3
      - ROUTER_NODES_2_HOST=backend-3
      - ROUTER_NODES_2_PORT=8083
    ports:
      - "8080:8080"
    depends_on:
      backend-1:
        condition: service_healthy
      backend-2:
        condition: service_healthy
      backend-3:
        condition: service_healthy
