version: '3.8'

services:
  eureka-server:
    image: nav2030/eureka-server:latest
    ports:
      - "8761:8761"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8761/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5

  backend-1:
    build:
      context: ./simple-backend-service
    environment:
      - SERVER_PORT=8081
      - BACKEND_ID=backend-1
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    ports:
      - "8081:8081"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8081/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      eureka-server:
        condition: service_healthy

  backend-2:
    build:
      context: ./simple-backend-service
    environment:
      - SERVER_PORT=8082
      - BACKEND_ID=backend-2
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    ports:
      - "8082:8082"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8082/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      eureka-server:
        condition: service_healthy

  backend-3:
    build:
      context: ./simple-backend-service
    environment:
      - SERVER_PORT=8083
      - BACKEND_ID=backend-3
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    ports:
      - "8083:8083"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8083/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      eureka-server:
        condition: service_healthy

  hash-router-service:
    build:
      context: ./hash-router-service
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - ROUTER_BACKEND_SERVICE_NAME=stateful-backend
    ports:
      - "8080:8080"
    depends_on:
      eureka-server:
        condition: service_healthy
      backend-1:
        condition: service_healthy
      backend-2:
        condition: service_healthy
      backend-3:
        condition: service_healthy
