user:
  subscription:
    prefix: USER_SUBSCRIPTION
jwt:
  secret-key: k7Yj9mP2vN5xR8wQ3tZ6bC1dF4gH7jK0lM3nO6pS9uV2wX5yA8=
  algorithm: HS256
spring:
  data:
    redis:
      host: localhost
      port: 6379
  kafka:
    bootstrap-servers: localhost:9092
    properties:
      spring.json.add.type.headers: false
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
