server:
  port: 8091

spring:
  application:
    name: user-service
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/bff_db
    username: admin
    password: admin

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  metrics:
    tags:
      application: ${spring.application.name}

logging:
  level:
    com.andver.bff.user: DEBUG
