version: "3.8"

services:
  redis:
    image: redis:7.2-alpine
    ports:
      - "6381:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10

  waiting-room-service:
    build:
      context: ./waiting-room-service
    ports:
      - "8100:8100"
    environment:
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
    depends_on:
      redis:
        condition: service_healthy
    restart: on-failure
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:8100/actuator/health >/dev/null || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 12
      start_period: 40s

  waiting-room-service-2:
    build:
      context: ./waiting-room-service
    ports:
      - "8102:8100"
    environment:
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
    depends_on:
      redis:
        condition: service_healthy
    restart: on-failure

  checkout-service:
    build:
      context: ./checkout-service
    ports:
      - "8101:8101"
    environment:
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      CHECKOUT_LATENCY: 200ms
      CHECKOUT_MAX_CONCURRENCY: 20
    depends_on:
      redis:
        condition: service_healthy
    restart: on-failure
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:8101/actuator/health >/dev/null || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 12
      start_period: 40s

  prometheus:
    image: prom/prometheus:v2.50.0
    ports:
      - "9095:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
      - waiting-room-service
      - checkout-service

  grafana:
    image: grafana/grafana:10.3.1
    ports:
      - "3003:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_USERS_ALLOW_SIGN_UP: "false"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
      - ./grafana/dashboards:/var/lib/grafana/dashboards:ro
    depends_on:
      - prometheus
