spring:
  application:
    name: simple-service
  kafka:
    bootstrap-servers: kafka:9092
server:
  port: 8080
dynamic-config:
  enabled: true
  bootstrap-servers: kafka:9092
  topic: config-state
  snapshot-topic: config-snapshot
management:
  endpoints:
    web:
      exposure:
        include: health,dynamic-config
