outbox:
  consumer:
    enabled: true
    topics: domain.order-created,domain.order-delivered
    group-id: notification-service-outbox

spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      auto-offset-reset: earliest
      enable-auto-commit: false
    listener:
      ack-mode: manual

  r2dbc:
    url: r2dbc:postgresql://localhost:5432/master
    username: demo
    password: demo
    pool:
      enabled: true
      initial-size: 5
      max-size: 10
      max-idle-time: 30m
      max-acquire-time: 30s
      max-create-connection-time: 30s