server:
  port: 8080

router:
  virtual-nodes-per-node: 150
  backend-service-name: ${ROUTER_BACKEND_SERVICE_NAME:stateful-backend}
  sync-interval-ms: ${ROUTER_SYNC_INTERVAL_MS:10000}

spring:
  application:
    name: hash-router

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
    fetch-registry: true
    register-with-eureka: false
