events { worker_connections 1024; }

http {
  upstream id_generator {
    server unique-id-generator-1:8080;
    server unique-id-generator-2:8080;
    server unique-id-generator-3:8080;
  }

  server {
    listen 8888;

    location / {
      proxy_pass http://id_generator;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
    }
  }
}
