events { worker_connections 1024; }

http {
  upstream spring_gateway {
    server gateway:8080;
  }

  server {
    listen 8888;

    location / {
      proxy_pass http://spring_gateway;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
      proxy_set_header Host $host;
    }
  }
}
