server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus,metrics
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: event-bridge

push:
  channel:
    prefix: PUSH_CHANNEL

spring:
  application:
    name: event-bridge
  data:
    redis:
      host: localhost
      port: 6379
  kafka:
    bootstrap-servers: localhost:9092
    properties:
      spring.json.add.type.headers: false
    consumer:
      group-id: push.event.bridge
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.value.default.type: com.andver.push.model.PushEvent
        spring.json.trusted.packages: "*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
