product-view:
  topic: product-view
  count-topic: product-view-counts
  window: PT1H
  threshold: 10
spring:
  kafka:
    bootstrap-servers: localhost:9092
    streams:
      application-id: trends-analyzer
      properties:
        default.key.serde: org.apache.kafka.common.serialization.Serdes$LongSerde
        default.value.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
